// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wintype.proto

#ifndef PROTOBUF_wintype_2eproto__INCLUDED
#define PROTOBUF_wintype_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace game {
namespace wintype {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_wintype_2eproto();
void protobuf_AssignDesc_wintype_2eproto();
void protobuf_ShutdownFile_wintype_2eproto();


enum WinType {
  WINTYPE_LOSE = 0,
  WINTYPE_JIULIANBAODENG = 1,
  WINTYPE_DASIXI = 2,
  WINTYPE_XIAOSIXI = 3,
  WINTYPE_DASANYUAN = 4,
  WINTYPE_SIANKE = 5,
  WINTYPE_SHIBALUOHAN = 6,
  WINTYPE_QINGYAOJIU = 7,
  WINTYPE_ZIYISE = 8,
  WINTYPE_XIAOSANYUAN = 9,
  WINTYPE_HUNYAOJIU = 10,
  WINTYPE_QINGDUI = 11,
  WINTYPE_QINPENG = 12,
  WINTYPE_HUNPENG = 13,
  WINTYPE_QINGYISE = 14,
  WINTYPE_HUNYISE = 15,
  WINTYPE_PENGPENGHU = 16,
  WINTYPE_PINGHU = 17,
  WINTYPE_JIHU = 18,
  WINTYPE_TIANHU = 19,
  WINTYPE_DIHU = 20,
  WINTYPE_RENHU = 21,
  WINTYPE_QIANGGANGHU = 22,
  WINTYPE_HAIDILAOYUE = 23,
  WINTYPE_GANGSHANGHUA = 24,
  WINTYPE_LONGQIDUi = 25,
  WINTYPE_QINGLONGQIDUI = 26,
  WINTYPE_QINQIDUI = 27,
  WINTYPE_QUANQIUREN = 28,
  WINTYPE_GANGSHANGPAO = 29,
  WINTYPE_MENQING = 30,
  WINTYPE_FENGYISE = 31,
  WINTYPE_MENQINGQINGYISE = 32,
  WINTYPE_QINGSIANKE = 33,
  WINTYPE_HAIDPAI = 34,
  WINTYPE_SHISANYAO = 35,
  WINTYPE_QIDUI = 36,
  WINTYPE_DAIYAOJIU = 37,
  WINTYPE_JIANGDUI = 38,
  WINTYPE_YITIAOLONG = 39,
  WINTYPE_QINYITIAOTONG = 40,
  WINTYPE_4JOKER = 41,
  WINTYPE_NOJOKER = 42,
  WINTYPE_QINGQUANQIUREN = 43,
  WINTYPE_CHANGSHA_SIXI = 512,
  WINTYPE_CHANGSHA_BANBANHU = 513,
  WINTYPE_CHANGSHA_QUEYIMEN = 514,
  WINTYPE_CHANGSHA_LIULIUSHUN = 515,
  WINTYPE_CHANGSHA_PENGPENGHU = 516,
  WINTYPE_CHANGSHA_JIANGJIANGHU = 517,
  WINTYPE_CHENZHOU_SIZHONGHU = 518
};
bool WinType_IsValid(int value);
const WinType WinType_MIN = WINTYPE_LOSE;
const WinType WinType_MAX = WINTYPE_CHENZHOU_SIZHONGHU;
const int WinType_ARRAYSIZE = WinType_MAX + 1;

const ::google::protobuf::EnumDescriptor* WinType_descriptor();
inline const ::std::string& WinType_Name(WinType value) {
  return ::google::protobuf::internal::NameOfEnum(
    WinType_descriptor(), value);
}
inline bool WinType_Parse(
    const ::std::string& name, WinType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<WinType>(
    WinType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace wintype
}  // namespace game
}  // namespace proto

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::proto::game::wintype::WinType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::proto::game::wintype::WinType>() {
  return ::proto::game::wintype::WinType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_wintype_2eproto__INCLUDED
